spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
  application:
    name: mall-auth
  # 统一的全局的--设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 关闭Thymeleaf的缓存
  redis:
    host: 192.168.91.131
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
server:
  port: 9010
  servlet:
    session:
      timeout: 30m # session超时30分钟