spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
  application:
    name: mall-cart
  thymeleaf:
    cache: false
  redis:
    host: 192.168.91.131
    port: 6379
server:
  port: 9020
