spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
  application:
    name: mall-search
  # 统一的全局的--设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8090