server:
  port: 8060
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
    sentinel:
      transport:
        dashboard: 192.168.91.131:8858
        client-ip: 192.168.91.127
        port: 8719
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: study-seekpan-mall
      sms:
        region-id: cn-beijing
        endpoint: dysmsapi.aliyuncs.com
        sign-name: 阿里云短信测试
        template-code: SMS_154950909
  application:
    name: mall-third
management:
  endpoints:
    web:
      exposure:
        include: '*'
