# 数据库的连接新
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.91.131:3306/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
    alibaba:
      seata:
        tx-service-group: mall-order-group
  application:
    name: mall-order
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: 192.168.91.131
    port: 6379
  # 统一的全局的--设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8030
  servlet:
    session:
      timeout: 30m
# RocketMQ的相关信息
rocketmq:
  name-server: 192.168.91.131:9876
  producer:
    group: order-producer
  consumer:
    group: order-consumer
alipay:
  appId: 9021000134649121
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiWtKukC9uaC7fbXSgVVOdR/6nwuhu1mjkWWHK2XuUKfpv61UHDuZTxIr15QaCZmaVI6ya8s+CyvDFNwiA6L8oMrXdfeHIhhd6SKFrDaOzfsvdg7tFj8hJ3kLd6W7dojs5rt72tbndbEAU1gkPn6py05ZPhTBcoOkGnwyKGZ1+gH/TXzQwH2oC/6CX0g0W3VR85QX54eFrCOfR8iBuQFVrZdG8F9Ia7uHAbsPUjn/BiA4WssibKjv/j+/uzNL12X/gDHMuggA364QLTmBIashB0gh5SeIQPDdD6uhR6fbSlwqY+nmKw+Lgq+u52ELdRmPf+JkWsQdeLwyFRuA0MNHfAgMBAAECggEAG6B42VuPtqnj0AFAJ0hdwhXOL53rD3FMyA6tpWb8sGm0Q/c3sMvIRdjcDJu8T9Q9AIPhizxmM0t1TRngSI9Sd/SpHded5BFtTVGuphjcEl8xMbCI3X1qB6famQhv5ScGDPrE1hZ2WkdhYCpLwGzbBE8c9MslP53iCU5nQ9i4BB50MXOKY8d/H+b7BD6Ew4otpSU8RXXC1RbR5llBswo17a/ODI8bIbLY8zWLI/17w038GDtH7gIZ+sDR9QMSUYHDTmT5L0znU5iGBq9ORQRz+IEcmSTbTupmhFa0sD07sB/QjynqsZb7/YPIHfsFGpqkoNnEdhJZOtTwThhtqCDEAQKBgQDUO9uOeXu8uxD+X3aikMQSvWematMp2EPn4pUN88xxfaqhzpHMMCteImDV3VpvpDYpG3ukehGV/Ecv2CigxDNhigvLbFeKmukRxQlKZEiXTNpUXyKVbBuAsLpSy76/89vlejIYhLjDTVZco1t/1HuC99LflXUthLCmAI+yenPuvwKBgQDD1caW2pcfVnvJ/zVg7VS69/xsKxu/xZnd15nbeFfFQy2DBLpeakJZ+Ys2eEp5JBMaGG3dB4XqxJjlDPn5KL2DtDSi4rb6j2xfMZROWrSIcP6Qm2fXBbII4GJT/MJDayNwcBSMd3899QnEq+bWXxxvJp+K3OZJ7/C9IPrbcK8E4QKBgQCvwoqHKTBCEiF2p5RV+NGIO3cVKK6LnuBNryWFknujGVEwAyRXFyUzJgFP26rDfhikXnA8vCLINU623qp2yUVL58jwxF6TGMsfvi99fiNnuWuuJ8M6P3dfUfxcCQOFb+yR1GqcR33Dr85vlZF3AX7v7VCjfOC3u4WXVCuswSA1fQKBgFZ0FYubTIPlJhjytZnorDMuLx2Bmmp6zYaGG8IrynOnSHxCphPwTQJzi+WsDRSVvGkUx8t/+rq9t9HGfMRmG+P8thACjkzm7CzKMnK00GY7m+Yy9RCTzxjkFgSF3SzuK2MD1857Io0zk/BjAzE4I9Fd96jSBEg3yMt1t8kQYfOBAoGBAJPIB0jNYbTL879DGuQpZscHUHHwzR2IlacKDM3Lb+qw5VJDTws6oNAuS+/49Em0SNfO+oYxujvpqHLqhe9811pmwjMRfLmczFzvcDwcWDEx60ZdnRHmaeuNYqNJwbQhC9AViJ5e1RloRHgomzy7xsoeNktm1n/3Pj1iJA3gSQEt
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkb/YfNr2FqTbiuEZ+SllEBO98G4xxaA0THGJfLOV8REFe4X5pbXT0Rhl+sn7kBvURKP74cnQbTe2Qbx3dUPUskuV3UtURPi47QulhrUaFXStABzmWFrR9jksJeuZ87h9tZuItpxH3wCY973EcRxtDB83EUMJizP1m95/AAhQZKPyqMPrQYc61KjrVUePy38dMMLkyJXLlY9KpqldfyJoERmXOs29HYEnaHEbGEHcIoMfFXf0uTBgBhI1dEMgmqWhYN40gnhtQVdE6dXHga2VBbQ4CmeDxPA7rIpRF4ZV1Nq3Ywek+lQSCi41f+WommccY64b/bJdr6lQ6XhyEpMNfQIDAQAB
  notifyUrl: http://ye10db1488083.vicp.fun/payed/notify
  returnUrl: http://order.msb.com/orderPay/returnUrl
